### ISSUE TITLE
Features

### ISSUE THREAD

**Issue by bennuttall** [piwheels/piwheels#1]
A feature-complete piwheels should:

- [x] be able to build ARM platform wheels which work on Raspberry Pi
- [x] be able to host wheels on a web server which are installable with pip
- [x] be able to log the status and output of each build
- [x] maintain an updated complete list of packages on PyPI, along with version numbers
- [x] be able to rebuild packages when new versions are released
- [x] be able to build ARMv7 wheels
- [x] be able to provide ARMv6 wheels
- [x] be able to build wheels for multiple Python versions
- [x] be able to publicly provide output from failed build attempts
- [x] be autonomous
- [x] be resilient to failure

**Comment by lurch** [comment]
Are the build-logs publicly viewable? If so, a link to them from http://www.piwheels.hostedpi.com/ would be nice ;-)

**Comment by waveform80** [comment]
Resilience to failure we're already pretty good at. While the monitor crashed a few times in the latest run (though I think I've fixed that in fc2e95fa37699d432e365f0f0d42a29e9803dac1), and the odd slave crashed when a huge C++ build wound up crashing the whole machine, the master itself didn't crash once in spite of the above failures.

@lurch build logs aren't *currently* publicly viewable but they have all been captured in the database. I'll see if I can include them in the JSON output envisaged for #16. If you want a copy in the meantime I can send you a dump of the postgres database (it's not terribly big - about 80Mb or so).

**Comment by waveform80** [comment]
Oh, sorry - make that 120Mb or so (hadn't checked since the latest run finished).

**Comment by lurch** [comment]
Ahhh, http://www.piwheels.hostedpi.com/ has changed since I wrote that comment ;-) IIRC at the time it was just a big directory-index of all the packages it had built (or perhaps I'm mis-remembering).

I was just thinking that for those packages that didn't get built successfully, it might be useful if the build-logs were publicly viewable (I was thinking in terms of a web-page rather than an API) so that package-maintainers could see what needed fixing, in order to get their package building properly on piwheels.

**Comment by waveform80** [comment]
Yeah, that huge list (required for pip) is now at http://www.piwheels.hostedpi.com/simple (**WARNING**: takes a *long* time to load in a browser) and you can see the indexes for individual packages beneath that, e.g. http://www.piwheels.hostedpi.com/simple/RPi.GPIO (worth noting if you check the source for the latter link that the links all include the SHA256 hash for download verification).

**Comment by lurch** [comment]
Hmmmm, https://www.piwheels.hostedpi.com/simple/RPi.GPIO/RPi.GPIO-0.6.3-cp34-cp34m-linux_armv7l.whl works, but https://www.piwheels.hostedpi.com/simple/RPi.GPIO/RPi.GPIO-0.6.3-cp34-cp34m-linux_armv6l.whl gives me a "Forbidden" error :confused:

**Comment by bennuttall** [comment]
That's odd. ARMv6 wheels are symlinks to the ARMv7 files and they're owned by the same user.

**Comment by lurch** [comment]
Maybe there's a setting in Apache that prevents it serving symlinks?

**Comment by lurch** [comment]
P.S. Given that the ARMv6 wheels are a symlink to the wheels that have been built for ARMv7, it seems a bit disingenuous for https://www.piwheels.hostedpi.com/ to claim "At present, piwheels only builds wheels for Python 3.4 on the armv6l architecture .... although these wheels are duplicated for the armv7l architecture" ?
(There's still part of me that wonders if one of the ARMv7 wheels might contain ARMv7-only instructions that wouldn't be able to run on an ARMv6 Raspberry Pi?)

**Comment by waveform80** [comment]
> P.S. Given that the ARMv6 wheels are a symlink to the wheels that have been built for ARMv7, it seems a bit disingenuous for https://www.piwheels.hostedpi.com/ to claim "At present, piwheels only builds wheels for Python 3.4 on the armv6l architecture .... although these wheels are duplicated for the armv7l architecture" ?
> (There's still part of me that wonders if one of the ARMv7 wheels might contain ARMv7-only instructions that wouldn't be able to run on an ARMv6 Raspberry Pi?)

Ahhh, it's *sort of* disingenuous but in the opposite way to what you're thinking :) All the build slaves are Pi3's and therefore they *think* they're building ARMv7 wheels. However, my understanding is that currently everything's really armv6 and just appears as armv7 because the Raspbian kernel lies about its architecture. Hence the statement that we're building armv6 wheels and duplicating for armv7 (in as much as we're building armv6 wheels that are *labelled* armv7 and then using symlinks to relabel them as armv6 ... but I didn't feel like explaining that in the webpage! :).

**Comment by lurch** [comment]
> However, my understanding is that currently everything's really armv6 and just appears as armv7 because the Raspbian kernel lies about its architecture.

Huh? I thought that's why there were two kernel images - `kernel.img` for ARMv6 and `kernel7.img` for ARMv7 ? \*confused\*

**Comment by bennuttall** [comment]
> Huh? I thought that's why there were two kernel images - kernel.img for ARMv6 and kernel7.img for ARMv7 ? *confused*

Correct. I *think* that's just for booting, but the OS runs in ARMv6 mode.

FWIW I think the wording is misleading. It's a lie mitigating a different lie. But I think it could be better phrased. I have a redraft I'll push later.

**Comment by lurch** [comment]
> Correct. I think that's just for booting, but the OS runs in ARMv6 mode.

Perhaps you could ask some of the RPF engineers for clarification? ;-)

**Comment by waveform80** [comment]
> Correct. I think that's just for booting, but the OS runs in ARMv6 mode.

Sorry, that's what I meant - that the userland is still ARMv6 and everything built in the userland is still ARMv6. But pip (or certain bits of pip, that ultimately lead back to Python's platform module) query uname to determine what architecture they're on; that reports armv7l ... which might be true for the kernel but is wrong for everything else, and lo ... my explanations descend into chaos! Anyway, the wording on the homepage is indeed mis-leading (deliberately to some degree) and whatever clarity anybody can offer is most welcome indeed :)

**Comment by lurch** [comment]
Aha, that's what I understood - ARMv7 kernel with ARMv6 userland. But if `pip` is using `uname` to query the arch to compile for, could it still end up with ARMv7-specific code inside the wheels? Or is the ARMv6 version of `gcc` unable to generate ARMv7-specific object code? \*shrug\*

**Comment by waveform80** [comment]
My understanding, limited as it is, is that the userland is still strictly ARMv6 and thus gcc will still generate ARMv6-compatible code - hence why we're happy to symlink wheels that are ostensibly ARMv7 to their equivalent ARMv6 name and serve them up as such. This is admittedly a lie and not good for any platform which is strictly ARMv7 only (i.e. any ARMv7 non-pi platform), but I'm hopeful the name "piwheels" makes it pretty clear this is a Pi-specific service (of course, it doesn't help anyone dealing with "armv7" wheels built by Pi users and registered on PyPI :)

**Comment by lurch** [comment]
AIUI a strictly ARMv6-only piwheel would work fine on a strictly ARMv7-only platform (ARMv7 is backwards-compatible with ARMv6), but the inverse _may_ not be true. I.e. a ARMv7-only piwheel _might_ not run on a ARMv6-only platform (like Raspbian running on a Pi1) _if_ it contains any ARMv7-specific instructions. But I believe (which might be an incorrect assumption!) in the majority of cases, most ARMv7-code probably doesn't contain any ARMv7-specific instructions, and so will still run fine on an ARMv6 CPU?

**Comment by waveform80** [comment]
That's also my understanding, architecturally for the Pi (though I'm also given to understand that non-Pi ARMv7 platforms aren't necessarily ARMv6 compatible). I'm also under the impression, perhaps mistakenly, that currently anything compiled on Raspbian on a v7 platform (say, a Pi 2) is v6 compatible as the whole userland (including compiler and libs) is v6. Happy to be corrected about any of the above!

And if anyone wants a crack at refining the notes on the homepage, the relevant file is [piwheels/master/index.template.html](https://github.com/bennuttall/piwheels/blob/master/piwheels/master/index.template.html). If you're wondering about the `{{` and `}}` it's because the whole thing gets chucked through Python's `str.format` call to fill in the stats, so bear that in mind for any patches.

**Comment by lurch** [comment]
> I'm also under the impression, perhaps mistakenly, that currently anything compiled on Raspbian on a v7 platform (say, a Pi 2) is v6 compatible as the whole userland (including compiler and libs) is v6.

I don't have time to test / investigate that myself, but again perhaps it'd be best for @bennuttall to ask some of the RPF engineers about that, as they're obviously the ones most likely to know the correct answers! ;-)

**Comment by bennuttall** [comment]
Almost all the items are complete now. @waveform80 do you think it's possible to share build output, perhaps via the prposed API rather than via web pages as originally suggested?

**Comment by waveform80** [comment]
Sure - I can add that pretty quickly as an extension to the index_scribe task (whenever it's prodded to rebuild the index for a package it queries everything it needs from the database anyway so that's an ideal time to grab other stuff like build output and dump it all in there).

Just one thing to bear in mind: the build output is *large* (it's the bulk of the database, and that's with pg compressing it all via TOAST) and JSON is not exactly an efficient format. I wouldn't be surprised if adding this chews up about 10Gb of drive space which is about all we've got left at the moment. Might be worth expanding the master's storage before we do this.

**Comment by lurch** [comment]
I'd question the usefulness of not being able to simply browse build output via a web-browser? :-/

(of course if those web-pages are dynamically served by an API back-end, rather than being statically generated, that's just fine :wink: )

**Comment by waveform80** [comment]
I can add both HTML and JSON quite easily. However, rather than burn lots and lots of drive space on this it might be better to have some "smart" HTML which grabs the build output from the associated JSON and renders it when requested?

**Comment by lurch** [comment]
...or you could use something like mod_rewrite and some clever .htaccess rules, so that none of the "JSON" or "HTML" files actually exist, but are instead dynamically generated on demand?
(basically just trading disk-usage for potential-CPU-load)

**Comment by waveform80** [comment]
It's certainly possible but there's some logistical issues with that:

Builds and any associated files are registered in the database upon completion *prior* to the files actually being transferred from the slave. This is because the database is used as the storage location for the file hashes so both the file transfer task and (later) the index writer task can use them without maintaining any communication with the build slaves themselves (I'm quite keen to keep the already spaghetti-like communication between the tasks as simple as I can reasonably manage).

Hence, if we dynamically generate the index.html within package directories it's possible to come up with something that lists packages that don't exist yet (that can't happen currently because the index writer task is only prodded by the file transfer task once it's certain all transfers are complete and hash-verified). We could refine that by checking both the database *and* the file-system (no need to worry about partial / corrupt transfers - files are transferred to temporary locations and renamed once verified) but at this point we're getting into quite a lot of IO to generate the index...

Remember the index.html for a package directory has to cover all available versions of a package. Looking at a large (but undoubtedly popular) example: numpy's currently got about 50 build attempts in the builds table, and 74 files listed in the files table. So that's 50 rows (including *big* build output) we've got to query (assuming we want to include build output), 74 relatively small rows to query and 74 extra stat calls to make against the file-system to check for existence of stuff.

And that's each time anyone on a Pi (with Raspbian Stretch) attempts a "pip install numpy" operation. And it's running on a Pi (albeit a Pi 3 with a fat NFS server backing it, but still). I don't want to shoot the idea down - I do think it's the "right" way of doing this (on a big box), but I'm a little nervous about that Pi being able to scale to the demand (whereas I'm quite sanguine about a web-server on there throwing static files at people).

Sidenote:

Why are we sticking with a Pi for all the serving stuff? Well Mythic are keen to prove that their hosting Pis in the cloud isn't just a gimmick and that it's actually useful for fairly serious projects. A laudable goal, and they're being very generous in donating Pi time (and space) to us for the piwheels project so I feel a certain obligation to try and help them achieve that.

The reason I quite like the "smart" HTML and JSON idea is that we burn a bit of space for the JSON (~10Gb as a rough estimate off the top of my head) but all the hard work (of loading and parsing that JSON) gets shunted to the client - we're still just static serving. It's also optional for the client to do that work (the pip client won't want the JSON when it's querying the index.html but it won't run any JS, so no harm done).

**Comment by lurch** [comment]
I'm confused - perhaps we're talking about different parts of the system?

> And that's each time anyone on a Pi (with Raspbian Stretch) attempts a "pip install numpy" operation.

I was merely talking about the build-log output, which I wouldn't expect `pip` to need? Obviously for frequently-accessed files like those needed by pip, it _does_ make sense to statically generate them.

My original point was that if the build-log files (which I'd expect to be accessed very rarely) take up too much disk-space, then they could be generated on demand, given that the info is (apparently) already stored in the database. But I obviously don't know how this whole system works, so I'll duck out again to avoid confusing matters even more ;-)

Oh, and reading @waveform80 's post again, it looks like he was imagining the build-logs being included in the same index.html as everything else? Given how rarely they'd be used, I was expecting the build-logs to be on a different page (linked to from index.html).

**Comment by waveform80** [comment]
> My original point was that if the build-log files (which I'd expect to be accessed very rarely) take up too much disk-space, then they could be generated on demand, given that the info is (apparently) already stored in the database. But I obviously don't know how this whole system works, so I'll duck out again to avoid confusing matters even more ;-)

Ahh - sorry, I missed the "on demand" bit! That makes a lot more sense :) I initially thought you were suggesting something more akin to a WSGI web-app (hence all the blah blah about scaling).

> Oh, and reading @waveform80 's post again, it looks like he was imagining the build-logs being included in the same index.html as everything else? Given how rarely they'd be used (and how big they are), I was expecting the build-logs to be on a different page (linked to from index.html).

My thought about including them in index.html was that that's where Ben originally had them in 0.1 which was convenient but, as we've noted, they're now quite huge especially as we're building every version of every package (0.1 only built the latest). Hence my pondering that it'd be nicer to have all that in a separate JSON file and have a little JS function in the HTML that loaded it if requested by the user.

Admittedly that's still burning space up front compared to generation on demand, but I'm still rather tempted by it simply because it's easy. At the moment the Apache config in piwheels is a brutally simple one: it serves static files from a directory we point it at, and that's it.

The master script that coordinates things dumps all the required files (wheels, HTML and a little CSS) in there periodically (in a fairly careful manner, ensuring that no partial files are ever available or at least "visible" to web clients).  There's no link at all between Apache and the master script and that makes certain maintenance jobs fairly easy (e.g. when it occasionally falls over because we encounter some new form of insanity in a package I can mess around and fix the master while Apache keeps on serving files, none the wiser to the chaos going on in the background :).

I think that's the route I'm going to pursue for now but I'll definitely bear the on-demand generation idea in mind. Depending on how much space we wind up burning I could well come back to it!

**Comment by bennuttall** [comment]
I was thinking we could provide a single JSON file for each package: the document would contain a list of versions, then build attempts for each version, with all required information contained within. That way the user would just inspect a single package's JSON document and loop over it for the build info. The file would be static, but updated after a build.

**Comment by bennuttall** [comment]
Errmm we should probably be discussing this in #16 not here :)
