### ISSUE TITLE
Don't use sudo by default

### ISSUE THREAD

**Issue by KTibow** [piwheels/piwheels#225]
In the official PyPi, it doesn't use `sudo`. Example: https://pypi.org/project/file-read-backwards/
![no sudo!](https://user-images.githubusercontent.com/10727862/84159687-326f8200-aa22-11ea-806c-ce3f7128598f.png)
Here's the corresponding issue:
https://github.com/pypa/pip/issues/1668
Here's the current implementation:
![uses sudo!](https://user-images.githubusercontent.com/10727862/84160017-92662880-aa22-11ea-9b56-2f4569546526.png)
It's understandable to use `sudo` for a whole-system installation, but it could be a problem with typosquatting. Maybe "sudo" should be in gray text? I'm not sure.

**Comment by bennuttall** [comment]
The problem is that `pip install x` doesn't work if `pip` isn't pointing at Python 3.

Since people use Raspberry Pi SD cards a bit like you might use a virtualenv on your main PC, it's common for people to just use system-wide installations.

However it's probably work pointing that out. It might be a good idea to add:

- an FAQ on sudo
- a link to the FAQ by the install box ("should I use sudo?")
- a button to toggle between `sudo pip3` and `pip`
